In [3]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('color_data.csv')

In [6]:
df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2343,2344,2345,2346,2347,2348,2349,2350,2351,label
0,0,10,5,2,10,5,2,10,5,2,...,10,5,2,10,5,2,10,5,2,black
1,1,17,0,17,17,0,17,17,0,17,...,17,0,17,17,0,17,17,0,17,black
2,2,29,24,23,29,24,23,29,24,23,...,29,24,23,29,24,23,29,24,23,black
3,3,47,47,47,47,47,47,47,47,47,...,47,47,47,47,47,47,47,47,47,black
4,4,28,29,33,28,29,33,28,29,33,...,28,29,33,28,29,33,28,29,33,black
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,245,255,187,22,255,183,8,255,183,9,...,255,183,9,255,183,8,255,187,22,yellow
246,246,255,255,0,255,255,0,255,255,0,...,255,255,0,255,255,0,255,255,0,yellow
247,247,255,166,0,255,166,0,255,166,0,...,255,166,0,255,166,0,255,166,0,yellow
248,248,249,217,94,249,217,94,249,217,94,...,249,217,94,249,217,94,249,217,94,yellow
249,249,246,191,39,246,191,39,246,191,39,...,246,191,39,246,191,39,246,191,39,yellow

In [19]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

LE = le.fit(df['label'].unique())
df['label'] = LE.transform(df['label'] )

In [20]:
df['label']

0      0
1      0
2      0
3      0
4      0
      ..
245    9
246    9
247    9
248    9
249    9
Name: label, Length: 250, dtype: int32

In [23]:
X = df.drop(['label'],axis=1)
y = df['label']

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Decision Tree Classifier

In [27]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.98

### K Nearest Neighbors (KNN) Classifier

In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.93
Accuracy of K-NN classifier on test set: 0.87